spring:
  datasource:
    url: jdbc:h2:mem:bookingdb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
server:
  port: 8080

app:
  integration:
    widget-script: "https://virtum-vr.com.ua/widget/booking.js"
